name = "greenbro-worker"
main = "dist/app.mjs"
compatibility_date = "2025-10-01"
compatibility_flags = ["nodejs_compat"]
minify = true

routes = [
  { pattern = "api.greenbro.co.za", custom_domain = true },
  { pattern = "dash.greenbro.co.za", custom_domain = true }
]

[build]
command = "npm run build"

[vars]
BUILD_SHA = "__BUILD_SHA__"
BUILD_DATE = "__BUILD_DATE__"
BUILD_SOURCE = "__BUILD_SOURCE__"

[triggers]
crons = ["0 2 * * *", "*/5 * * * *", "15 2 1 * *"]


[durable_objects]
bindings = [
  { name = "DeviceState", class_name = "DeviceStateDO" },
  { name = "DEVICE_DO", class_name = "DeviceDO" }
]

[[migrations]]
tag = "v1-device-state"
new_classes = ["DeviceStateDO"]

[[migrations]]
tag = "v2-device"
new_classes = ["DeviceDO"]

[[d1_databases]]
binding = "DB"
database_name = "GREENBRO_DB"
database_id = "4e2ddbf4-a12d-4a36-8e10-4a1a57f41d38"

[[r2_buckets]]
binding = "REPORTS"
bucket_name = "greenbro-reports"

[[r2_buckets]]
binding = "BRAND"
bucket_name = "greenbro-brand"

[[r2_buckets]]
binding = "ARCHIVE"
bucket_name = "greenbro-archive"

[[kv_namespaces]]
binding = "CONFIG"
id = "01ab23cd4567890efabc1234567890de"

[env.staging]
vars.ACCESS_AUD = "https://access.greenbro.co.za"
vars.ACCESS_ISS = "https://access.greenbro.co.za"
vars.ACCESS_JWKS = "https://access.greenbro.co.za/cdn-cgi/access/certs"
vars.BUILD_SHA = "__BUILD_SHA__"
vars.BUILD_DATE = "__BUILD_DATE__"
vars.BUILD_SOURCE = "__BUILD_SOURCE__"

[[env.staging.d1_databases]]
binding = "DB"
database_id = "4e2ddbf4-a12d-4a36-8e10-4a1a57f41d38"
database_name = "GREENBRO_DB"

[[env.staging.r2_buckets]]
binding = "REPORTS"
bucket_name = "greenbro-reports"

[[env.staging.r2_buckets]]
binding = "BRAND"
bucket_name = "greenbro-brand"

[[env.staging.r2_buckets]]
binding = "ARCHIVE"
bucket_name = "greenbro-archive"

[[env.staging.kv_namespaces]]
binding = "CONFIG"
id = "01ab23cd4567890efabc1234567890de"

[env.staging.durable_objects]
bindings = [
  { name = "DeviceState", class_name = "DeviceStateDO" },
  { name = "DEVICE_DO", class_name = "DeviceDO" }
]

[env.production]
vars.ACCESS_AUD = "https://access.greenbro.co.za"
vars.ACCESS_ISS = "https://access.greenbro.co.za"
vars.ACCESS_JWKS = "https://access.greenbro.co.za/cdn-cgi/access/certs"
vars.BUILD_SHA = "__BUILD_SHA__"
vars.BUILD_DATE = "__BUILD_DATE__"
vars.BUILD_SOURCE = "__BUILD_SOURCE__"

[[env.production.d1_databases]]
binding = "DB"
database_id = "a2b6e0f1-2a3b-4c5d-9e6f-1234567890ab"
database_name = "greenbro-db-prod"

[[env.production.r2_buckets]]
binding = "REPORTS"
bucket_name = "greenbro-reports-prod"

[[env.production.r2_buckets]]
binding = "BRAND"
bucket_name = "greenbro-brand-prod"

[[env.production.r2_buckets]]
binding = "ARCHIVE"
bucket_name = "greenbro-archive-prod"

[[env.production.kv_namespaces]]
binding = "CONFIG"
id = "f8d2c3a4b5e6471c9d0ef123456789ab"

[env.production.durable_objects]
bindings = [
  { name = "DeviceState", class_name = "DeviceStateDO" },
  { name = "DEVICE_DO", class_name = "DeviceDO" }
]
