name = "greenbro-heat-pump-app-2025"
account_id = "0bee3514d14fef8558ccaf0bf2b72eb1"
main = "dist/app.mjs"
compatibility_date = "2025-10-01"
compatibility_flags = ["nodejs_compat"]
minify = true

routes = [
  { pattern = "api.greenbro.co.za", custom_domain = true },
  { pattern = "dash.greenbro.co.za", custom_domain = true }
]

[build]
command = "npm run build"

[vars]
BUILD_SHA = "__BUILD_SHA__"
BUILD_DATE = "__BUILD_DATE__"
BUILD_SOURCE = "__BUILD_SOURCE__"

[triggers]
crons = ["0 2 * * *", "*/5 * * * *", "15 2 1 * *"]


[durable_objects]
bindings = [
  { name = "DeviceState", class_name = "DeviceStateDO" },
  { name = "DEVICE_DO", class_name = "DeviceDO" }
]

[[migrations]]
tag = "v1-device-state"
new_classes = ["DeviceStateDO"]

[[migrations]]
tag = "v2-device"
new_classes = ["DeviceDO"]

[[d1_databases]]
binding = "DB"
database_name = "GREENBRO_DB_STAGING"
database_id = "9ab01dd1-441c-452c-b439-55d9aa5938ab"

[[r2_buckets]]
binding = "REPORTS"
bucket_name = "greenbro-reports"

[[r2_buckets]]
binding = "BRAND"
bucket_name = "greenbro-brand"

[[r2_buckets]]
binding = "ARCHIVE"
bucket_name = "greenbro-archive"

[[kv_namespaces]]
binding = "CONFIG"
id = "e9509ebd5bbb487e8e1698db35bfa439"

[env.staging]
vars.ACCESS_AUD = "558e7450465163f7be473dcb75d5cea6d786f7143f3fcfe4dc658049c47c5e0b"
vars.ACCESS_ISS = "https://bradleyayliffl.cloudflareaccess.com"
vars.ACCESS_JWKS = "https://bradleyayliffl.cloudflareaccess.com/cdn-cgi/access/certs"
vars.BUILD_SHA = "__BUILD_SHA__"
vars.BUILD_DATE = "__BUILD_DATE__"
vars.BUILD_SOURCE = "__BUILD_SOURCE__"

[[env.staging.d1_databases]]
binding = "DB"
database_id = "9ab01dd1-441c-452c-b439-55d9aa5938ab"
database_name = "GREENBRO_DB_STAGING"

[[env.staging.r2_buckets]]
binding = "REPORTS"
bucket_name = "greenbro-reports-staging"

[[env.staging.r2_buckets]]
binding = "BRAND"
bucket_name = "greenbro-brand-staging"

[[env.staging.r2_buckets]]
binding = "ARCHIVE"
bucket_name = "greenbro-archive-staging"

[[env.staging.kv_namespaces]]
binding = "CONFIG"
id = "e9509ebd5bbb487e8e1698db35bfa439"

[env.staging.durable_objects]
bindings = [
  { name = "DeviceState", class_name = "DeviceStateDO" },
  { name = "DEVICE_DO", class_name = "DeviceDO" }
]

[env.production]
vars.ACCESS_AUD = "965324499988b497906c949af33be0c457edff0b9ac3edf8d287825b7d7af78d"
vars.ACCESS_ISS = "https://bradleyayliffl.cloudflareaccess.com"
vars.ACCESS_JWKS = "https://bradleyayliffl.cloudflareaccess.com/cdn-cgi/access/certs"
vars.BUILD_SHA = "__BUILD_SHA__"
vars.BUILD_DATE = "__BUILD_DATE__"
vars.BUILD_SOURCE = "__BUILD_SOURCE__"

[[env.production.d1_databases]]
binding = "DB"
database_id = "4e2ddbf4-a12d-4a36-8e10-4a1a57f41d38"
database_name = "GREENBRO_DB"

[[env.production.r2_buckets]]
binding = "REPORTS"
bucket_name = "greenbro-reports"

[[env.production.r2_buckets]]
binding = "BRAND"
bucket_name = "greenbro-brand"

[[env.production.r2_buckets]]
binding = "ARCHIVE"
bucket_name = "greenbro-archive"

[[env.production.kv_namespaces]]
binding = "CONFIG"
id = "14ee885ce1ab45738c2619bd56a11361"

[env.production.durable_objects]
bindings = [
  { name = "DeviceState", class_name = "DeviceStateDO" },
  { name = "DEVICE_DO", class_name = "DeviceDO" }
]
